# -*- coding: utf-8 -*-
"""Pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t7tSsytIIMW_20DGR5bGMBF366aMT1y1
"""

pip install pandas

import pandas as pd
prices=[2999,15999,52099,32133,1213]
products=["wireless earbuds", "smartphone","laptop","bluetooth speaker","airpods"]
product_prices=pd.Series(prices,index=products)
print(product_prices)

print("Mean:",product_prices.mean())
print("Sum:",product_prices.sum())
print("Maximum:",product_prices.max())
print("Minimum:",product_prices.min())

print("Head (First 3 elements):\n", product_prices.head(3))
print("Tail (First 2 elements):\n", product_prices.tail(2))

print("Apply (Adding 18% GST):\n", product_prices.apply(lambda x: f"${x+(x*0.18)}"))
print("Map (Formatting as Currency):\n", product_prices.map(lambda x: f"${x}.00"))

print(product_prices.sort_values())

print(product_prices.sort_index())

print(product_prices.sort_index(ascending=True))

print("Value Counts:\n", product_prices.value_counts())