# -*- coding: utf-8 -*-
"""WebScraping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GyHOThbIldse24jVtlKxvQc0BANcw8T4
"""

#Loading Required libraries
import requests
from bs4 import BeautifulSoup

URL="https://codegnan.com"

#Loading the Webpage in Memory using requests library
page=requests.get(URL)

#Check the status Code of the Page
page.status_code

htmlCode=page.text
print(htmlCode)

soup=BeautifulSoup(htmlCode, "html.parser")
print(soup)

title=soup.title.text
print("Website.Title:", title)

headings=soup.find_all("h3")
for heading in headings:
    print(heading.text.strip())

links=soup.find_all("a")
for link in links[:10]:       #First 10 Links
  print(link.get("href"))

images=soup.find_all("img")
for image in images[:10]:
    print(image.get("src"))

description=soup.find_all("meta", attrs={"name":"description"})
if description:
    print("Description:")
    print(description[0].get("content"))

for tag in soup.find_all():
    if tag.get("class"):
      print(tag.get("class"))

scripts = soup.find_all("scripts")
for script in scripts:
  print(script.get("src"))

logo = soup.find("img")
print(logo.get("src"))

og_image = soup.find("meta", attrs={"property":"og:image"})
if og_image:
  print(og_image.get("content"))

og_title = soup.find("meta", attrs={"property":"og:title"})
if og_title:
  print(og_title.get("content"))

meta_tags=soup.find_all("meta")
for tag in meta_tags:
  if tag.get("name") == "description":
    print(tag.get("content"))

menus = soup.find_all("li")
for menu in menus[:20]:
  print(menu.text.strip())

paragraphs=soup.find_all("p")
for paragraph in paragraphs[:10]:
  print(paragraph.text.strip())

buttons=soup.find_all("button")
for button in buttons:
  print(button.text.strip())